tareas = ["abrir los ojos", "desayunar", "lavarse los dientes", "bañarse y vestirse", "go to cs50"]
tareas.append("cocinar")
tareas.insert(0, "soñar")
print(tareas)
tareas.remove("go to cs50")
print(tareas)
eliminado = tareas.pop()
print(len(tareas))
tareas.sort()
print(tareas)
tareas.reverse()
print(tareas)
